### ISSUE TITLE
Реализация предметов

### ISSUE THREAD

**Issue by JamPeregar** [JamPeregar/Java_MagicQuest#1]
1) Можно использовать синглетоны и создавать класс под каждый предмет или его вид.

2) Вероятно возможно использовать фабричный метод .... Класс-фабрику предметов. Может оно будет прямо на локациях

**Comment by RinKirsan** [comment]
как я понял синглетоны позволяют создать только один экземпляр класса. А если нам нужно создать два одинаковых предмета, то получается нам нужно создавать ещё один синглетон под второй предмет?

**Comment by JamPeregar** [comment]
Ладно, без синглетонов, но проблема использования 2х предметов за раз решена?
